# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('anthocnet-example', ['core', 'wifi' ,'anthocnet', 'aodv'])
    obj.source = ['anthocnet-example.cc',
        'manet-routing-compare.cc']

