# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('anthocnet-compare', ['core', 'wifi' ,'anthocnet', 'aodv', 'applications', 'flow-monitor'])
    obj.source = ['manet-routing-compare.cc']
    
    obj = bld.create_ns3_program('anthocnet-example', ['core', 'anthocnet'])
    obj.source = ['anthocnet-example.cc']

