# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):
    obj = bld.create_ns3_program('anthocnet-compare', ['core','wifi', 'stats', 'anthocnet', 'aodv', 'applications', 'flow-monitor', 'netanim'])
    obj.source = ['anthocnet-routing-compare.cc']
    
    obj = bld.create_ns3_program('anthocnet-example', ['core', 'anthocnet'])
    obj.source = ['anthocnet-example.cc']

